const { NlpManager } = require('node-nlp');
const manager = new NlpManager({ languages: ['en'], forceNER: true });

manager.addDocument('en', "Could you make this change?", 'request');
manager.addDocument('en', "I suggest we update this part.", 'request');
manager.addDocument('en', "It would be cool if you could add", 'request');
manager.addDocument('en', "It would be great if this could be improved:", 'request');
manager.addDocument('en', "Could you consider changing", 'request');
manager.addDocument('en', "Perhaps you could enhance", 'request');
manager.addDocument('en', "Is it possible to modify", 'request');
manager.addDocument('en', "Can you add functionality for", 'request');
manager.addDocument('en', "I'd like to request a feature:", 'request');
manager.addDocument('en', "I need this part to be updated:", 'request');
manager.addDocument('en', "Please help me with this change:", 'request');
manager.addDocument('en', "Could you assist me in implementing", 'request');
manager.addDocument('en', "I'm looking for an improvement in", 'request');
manager.addDocument('en', "Would you mind adding support for", 'request');
manager.addDocument('en', "You should totally add this feature.", 'request');
manager.addDocument('en', "It'd be awesome if you could implement this.", 'request');
manager.addDocument('en', "You gotta make this change.", 'request');
manager.addDocument('en', "Can you, like, please add this?", 'request');
manager.addDocument('en', "Maybe you could, like, consider improving this.", 'request');
manager.addDocument('en', "Is it like possible to enhance this part?", 'request');
manager.addDocument('en', "Could you hook me up with more info?", 'request');
manager.addDocument('en', "I'd love to see some updates here.", 'request');
manager.addDocument('en', "I need this to be more user-friendly.", 'request');
manager.addDocument('en', "Help me out with this change:", 'request');
manager.addDocument('en', "Could you, like, assist me in implementing this feature?", 'request');
manager.addDocument('en', "I'm really into this idea. Can you make it happen?", 'request');
manager.addDocument('en', "Would you mind adding support for this?", 'request');
manager.addDocument('en', "I want you to make it happen:", 'request');
manager.addDocument('en', "I'm looking for information on this improvement.", 'request');
manager.addDocument('en', "Can you make this adjustment?", 'request');
manager.addDocument('en', "I propose we enhance this section.", 'request');
manager.addDocument('en', "It would be fantastic if you could include this.", 'request');
manager.addDocument('en', "It would be wonderful if this could be optimized:", 'request');
manager.addDocument('en', "Could you contemplate altering", 'request');
manager.addDocument('en', "Maybe you could elevate", 'request');
manager.addDocument('en', "Is it feasible to tweak", 'request');
manager.addDocument('en', "Can you introduce functionality for", 'request');
manager.addDocument('en', "I'd like to suggest a feature:", 'request');
manager.addDocument('en', "I require an update for this part:", 'request');
manager.addDocument('en', "Please assist me with this modification:", 'request');
manager.addDocument('en', "Could you guide me in implementing", 'request');
manager.addDocument('en', "I'm seeking an enhancement in", 'request');
manager.addDocument('en', "Would you be open to adding support for", 'request');
manager.addDocument('en', "You absolutely should implement this feature.", 'request');
manager.addDocument('en', "It'd be incredible if you could execute this.", 'request');
manager.addDocument('en', "You must make this alteration.", 'request');
manager.addDocument('en', "Can you, pretty please, include this?", 'request');
manager.addDocument('en', "Perhaps you could contemplate improving this.", 'request');
manager.addDocument('en', "Is it possible to enhance this segment?", 'request');
manager.addDocument('en', "Could you provide me with more details?", 'request');
manager.addDocument('en', "I'd be thrilled to witness updates here.", 'request');
manager.addDocument('en', "I require this to be more user-friendly.", 'request');
manager.addDocument('en', "Lend me a hand with this modification:", 'request');
manager.addDocument('en', "Could you kindly assist me in implementing this functionality?", 'request');
manager.addDocument('en', "I'm genuinely enthusiastic about this concept. Can you bring it to life?", 'request');
manager.addDocument('en', "Would you be willing to add support for this?", 'request');
manager.addDocument('en', "I'd like to see this become a reality:", 'request');
manager.addDocument('en', "I'm in search of information regarding this enhancement.", 'request');
manager.addDocument('en', "You absolutely must include this feature.", 'request');
manager.addDocument('en', "It'd be outstanding if you could execute this.", 'request');
manager.addDocument('en', "You need to make this change happen.", 'request');
manager.addDocument('en', "Could you, with all due respect, incorporate this?", 'request');
manager.addDocument('en', "Maybe you could explore the possibility of enhancing this.", 'request');
manager.addDocument('en', "Is it feasible to improve this section?", 'request');
manager.addDocument('en', "Could you provide me with additional information?", 'request');
manager.addDocument('en', "I'd greatly appreciate updates in this area.", 'request');
manager.addDocument('en', "I'm looking for this to be more user-centric.", 'request');
manager.addDocument('en', "Lend me your expertise with this adjustment:", 'request');
manager.addDocument('en', "Could you kindly guide me in implementing this functionality?", 'request');
manager.addDocument('en', "I'm genuinely excited about this concept. Can you make it a reality?", 'request');
manager.addDocument('en', "Would you be open to including support for this?", 'request');
manager.addDocument('en', "I'd love to see this implemented:", 'request');
manager.addDocument('en', "I'm seeking information regarding this improvement.", 'request');


manager.addDocument('en', "You should try going to", 'suggestion');
manager.addDocument('en', "Try asking", 'suggestion');
manager.addDocument('en', "There is a place you can", 'suggestion');
manager.addDocument('en', "There is a way to", 'suggestion');
manager.addDocument('en', "I would suggest", 'suggestion');
manager.addDocument('en', "I would try to", 'suggestion');
manager.addDocument('en', "If it was me I would", 'suggestion');
manager.addDocument('en', "How about instead you", 'suggestion');
manager.addDocument('en', "You might find it beneficial to explore", 'suggestion');
manager.addDocument('en', "Consider the option of asking", 'suggestion');
manager.addDocument('en', "Take a look at this place:", 'suggestion');
manager.addDocument('en', "One approach to consider is:", 'suggestion');
manager.addDocument('en', "I'd recommend thinking about", 'suggestion');
manager.addDocument('en', "Why not attempt to", 'suggestion');
manager.addDocument('en', "You could give this a shot:", 'suggestion');
manager.addDocument('en', "Here's an alternative: try", 'suggestion');
manager.addDocument('en', "Have you considered trying", 'suggestion');
manager.addDocument('en', "It might be worth experimenting with", 'suggestion');
manager.addDocument('en', "You can test out", 'suggestion');
manager.addDocument('en', "Another option is to", 'suggestion');
manager.addDocument('en', "You could explore the idea of", 'suggestion');
manager.addDocument('en', "Why not give this a go:", 'suggestion');
manager.addDocument('en', "It's worth thinking about", 'suggestion');
manager.addDocument('en', "How about giving this a try:", 'suggestion');


manager.addDocument('en', "Can you provide more details?", 'question');
manager.addDocument('en', "Could you explain further?", 'question');
manager.addDocument('en', "I'd like more information about this.", 'question');
manager.addDocument('en', "Could you help me understand better?", 'question');
manager.addDocument('en', "Can you clarify something for me?", 'question');
manager.addDocument('en', "I need more info on this topic.", 'question');
manager.addDocument('en', "Can you explain the process?", 'question');
manager.addDocument('en', "What are the steps to do this?", 'question');
manager.addDocument('en', "I'm curious about how to", 'question');
manager.addDocument('en', "What's the procedure to", 'question');
manager.addDocument('en', "Can you provide guidance on", 'question');
manager.addDocument('en', "Can you provide insights into", 'question');
manager.addDocument('en', "Could you share more details about", 'question');
manager.addDocument('en', "Can you give me more context on", 'question');
manager.addDocument('en', "What's the recommended way to", 'question');
manager.addDocument('en', "Can you provide more details about this topic?", 'question');
manager.addDocument('en', "Could you explain this further?", 'question');
manager.addDocument('en', "I'd like more information about this subject.", 'question');
manager.addDocument('en', "Could you help me understand this better?", 'question');
manager.addDocument('en', "Can you clarify something about this?", 'question');
manager.addDocument('en', "I need more info on this subject.", 'question');
manager.addDocument('en', "Can you explain the process behind this?", 'question');
manager.addDocument('en', "What are the steps to do this task?", 'question');
manager.addDocument('en', "I'm curious about how to accomplish this.", 'question');
manager.addDocument('en', "What's the procedure for this action?", 'question');
manager.addDocument('en', "Can you provide guidance on this matter?", 'question');
manager.addDocument('en', "Can you provide insights into this topic?", 'question');
manager.addDocument('en', "Could you share more details about this subject?", 'question');
manager.addDocument('en', "Can you give me more context on this issue?", 'question');
manager.addDocument('en', "What's the recommended way to approach this?", 'question');
manager.addDocument('en', "Could you provide additional information?", 'question');
manager.addDocument('en', "Can you delve deeper into this?", 'question');
manager.addDocument('en', "I'd appreciate a deeper understanding of this.", 'question');
manager.addDocument('en', "Could you assist me in comprehending better?", 'question');
manager.addDocument('en', "Can you shed light on a particular aspect for me?", 'question');
manager.addDocument('en', "I require further insight into this topic.", 'question');
manager.addDocument('en', "Can you elucidate the process?", 'question');
manager.addDocument('en', "What are the necessary steps for this?", 'question');
manager.addDocument('en', "I'm intrigued by how to", 'question');
manager.addDocument('en', "What's the method for", 'question');
manager.addDocument('en', "Can you offer guidance on this matter?", 'question');
manager.addDocument('en', "Can you provide deeper insights into", 'question');
manager.addDocument('en', "Could you disclose more details about", 'question');
manager.addDocument('en', "Can you provide me with additional context on", 'question');
manager.addDocument('en', "What's the best approach to", 'question');
manager.addDocument('en', "Can you give me more information on this topic?", 'question');
manager.addDocument('en', "Could you elaborate on this further?", 'question');
manager.addDocument('en', "I'd like to delve deeper into this subject.", 'question');
manager.addDocument('en', "Could you aid me in understanding this better?", 'question');
manager.addDocument('en', "Can you clarify a particular point about this?", 'question');
manager.addDocument('en', "I need further information on this subject.", 'question');
manager.addDocument('en', "Can you expound on the process behind this?", 'question');
manager.addDocument('en', "What are the requisite steps for this task?", 'question');
manager.addDocument('en', "I'm curious about the process of", 'question');
manager.addDocument('en', "What's the prescribed procedure for this action?", 'question');
manager.addDocument('en', "Can you provide expert guidance on this matter?", 'question');
manager.addDocument('en', "Can you offer profound insights into this topic?", 'question');
manager.addDocument('en', "Could you reveal more details about this subject?", 'question');
manager.addDocument('en', "Can you provide a deeper context on this issue?", 'question');
manager.addDocument('en', "What's the recommended approach for handling this?", 'question');
manager.addDocument('en', "Could you furnish additional information?", 'question');
manager.addDocument('en', "Can you go into more depth on this?", 'question');
manager.addDocument('en', "I'd like to gain a better understanding of this.", 'question');
manager.addDocument('en', "Could you help me grasp this concept better?", 'question');
manager.addDocument('en', "Can you clarify a specific aspect of this?", 'question');
manager.addDocument('en', "I need further insights into this topic.", 'question');
manager.addDocument('en', "Can you elucidate the process in detail?", 'question');
manager.addDocument('en', "What are the step-by-step instructions for this task?", 'question');
manager.addDocument('en', "I'm keen on understanding the procedure for", 'question');
manager.addDocument('en', "What's the proper protocol for this action?", 'question');
manager.addDocument('en', "Can you provide comprehensive guidance on this matter?", 'question');
manager.addDocument('en', "Can you offer in-depth insights into this topic?", 'question');
manager.addDocument('en', "Could you share detailed information about this subject?", 'question');
manager.addDocument('en', "Can you give me a more comprehensive context on this issue?", 'question');
manager.addDocument('en', "What's the most effective approach for this?", 'question');
manager.addDocument('en', "Hey have you", 'question');
manager.addDocument('en', "Did you manage to", 'question');
manager.addDocument('en', "Who is", 'question');
manager.addDocument('en', "Where is that at?", 'question');
manager.addDocument('en', "Who is it?", 'question');


manager.addDocument('en', "Great job on", 'positive');
manager.addDocument('en', "I'm impressed by", 'positive');
manager.addDocument('en', "Well done with", 'positive');
manager.addDocument('en', "I love", 'positive');
manager.addDocument('en', "You're amazing at", 'positive');
manager.addDocument('en', "Kudos for", 'positive');
manager.addDocument('en', "Excellent work on", 'positive');
manager.addDocument('en', "I'm grateful for", 'positive');
manager.addDocument('en', "You've done an awesome job on", 'positive');
manager.addDocument('en', "I'm so pleased with", 'positive');
manager.addDocument('en', "Bravo for", 'positive');
manager.addDocument('en', "I appreciate your work on", 'positive');
manager.addDocument('en', "Your effort on", 'positive');
manager.addDocument('en', "You've exceeded my expectations with", 'positive');
manager.addDocument('en', "Thanks for your support.", 'positive');
manager.addDocument('en', "I appreciate your help.", 'positive');
manager.addDocument('en', "You've been so helpful.", 'positive');
manager.addDocument('en', "Great job sending the info.", 'positive');
manager.addDocument('en', "You're the best.", 'positive');
manager.addDocument('en', "I'm grateful for your assistance.", 'positive');
manager.addDocument('en', "Hi there! I'm feeling great today.", 'positive');
manager.addDocument('en', "Hello, I'm having an awesome day.", 'positive');
manager.addDocument('en', "Hey! It's nice to see you again.", 'positive');
manager.addDocument('en', "Good morning! I'm in a fantastic mood.", 'positive');
manager.addDocument('en', "Hi, how's it going? I'm doing wonderfully.", 'positive');
manager.addDocument('en', "Hello, I hope you're well. I'm really happy.", 'positive');
manager.addDocument('en', "Hey, it's a beautiful day! I'm feeling cheerful.", 'positive');
manager.addDocument('en', "Good afternoon! I'm having a fantastic time.", 'positive');
manager.addDocument('en', "Hi there, friend! I'm filled with joy.", 'positive');
manager.addDocument('en', "Hello, everyone! I'm thrilled to be here.", 'positive');
manager.addDocument('en', "Outstanding work on that project!", 'positive');
manager.addDocument('en', "I'm really impressed with your performance.", 'positive');
manager.addDocument('en', "Excellent job handling that situation.", 'positive');
manager.addDocument('en', "You're doing a fantastic job!", 'positive');
manager.addDocument('en', "I'm thrilled with the results.", 'positive');
manager.addDocument('en', "You make everything so much better!", 'positive');
manager.addDocument('en', "I'm grateful for your hard work.", 'positive');
manager.addDocument('en', "You've exceeded my expectations.", 'positive');
manager.addDocument('en', "Thanks for your exceptional support.", 'positive');
manager.addDocument('en', "Your assistance has been invaluable.", 'positive');
manager.addDocument('en', "I couldn't be happier with your service.", 'positive');
manager.addDocument('en', "You're a true professional.", 'positive');
manager.addDocument('en', "I appreciate your dedication.", 'positive');
manager.addDocument('en', "You've made my day with your help.", 'positive');
manager.addDocument('en', "I can always count on you.", 'positive');
manager.addDocument('en', "You're a rockstar!", 'positive');
manager.addDocument('en', "I'm so grateful for your support.", 'positive');
manager.addDocument('en', "You're a lifesaver.", 'positive');
manager.addDocument('en', "Your assistance is invaluable.", 'positive');
manager.addDocument('en', "You're a true asset to the team.", 'positive');
manager.addDocument('en', "I hope you feel better.", 'positive');
manager.addDocument('en', "I'm thrilled with your service.", 'positive');
manager.addDocument('en', "This exceeded my expectations.", 'positive');
manager.addDocument('en', "I'm impressed by your team's efforts.", 'positive');
manager.addDocument('en', "You're doing a fantastic job!", 'positive');
manager.addDocument('en', "Kudos to your customer support.", 'positive');
manager.addDocument('en', "Impressive work on", 'positive');
manager.addDocument('en', "I'm amazed by", 'positive');
manager.addDocument('en', "Well executed with", 'positive');
manager.addDocument('en', "I adore", 'positive');
manager.addDocument('en', "You're exceptional at", 'positive');
manager.addDocument('en', "Thumbs up for", 'positive');
manager.addDocument('en', "Outstanding performance on", 'positive');
manager.addDocument('en', "I'm thankful for", 'positive');
manager.addDocument('en', "You've excelled on", 'positive');
manager.addDocument('en', "I'm delighted with", 'positive');
manager.addDocument('en', "Hats off for", 'positive');
manager.addDocument('en', "I value your work on", 'positive');
manager.addDocument('en', "Your dedication to", 'positive');
manager.addDocument('en', "You've surpassed my expectations with", 'positive');
manager.addDocument('en', "Appreciate your support.", 'positive');
manager.addDocument('en', "I'm grateful for your assistance.", 'positive');
manager.addDocument('en', "You've been highly helpful.", 'positive');
manager.addDocument('en', "Exceptional job on providing the information.", 'positive');
manager.addDocument('en', "You're truly outstanding.", 'positive');
manager.addDocument('en', "I'm appreciative of your help.", 'positive');
manager.addDocument('en', "Hey there! Feeling good today.", 'positive');
manager.addDocument('en', "Hello, having a great day.", 'positive');
manager.addDocument('en', "Hey! Nice to see you again.", 'positive');
manager.addDocument('en', "Good morning! Feeling fantastic.", 'positive');
manager.addDocument('en', "Hi, how's it going? Doing wonderfully.", 'positive');
manager.addDocument('en', "Hello, hope you're well. I'm really happy.", 'positive');
manager.addDocument('en', "Hey, it's a beautiful day! Feeling cheerful.", 'positive');
manager.addDocument('en', "Good afternoon! Having a fantastic time.", 'positive');
manager.addDocument('en', "Hi there, friend! Filled with joy.", 'positive');
manager.addDocument('en', "Hello, everyone! Thrilled to be here.", 'positive');
manager.addDocument('en', "Exceptional work on that project!", 'positive');
manager.addDocument('en', "I'm genuinely impressed with your performance.", 'positive');
manager.addDocument('en', "Exceptional job handling that situation.", 'positive');
manager.addDocument('en', "You're doing a remarkable job!", 'positive');
manager.addDocument('en', "I'm thrilled with the results.", 'positive');
manager.addDocument('en', "You elevate everything!", 'positive');
manager.addDocument('en', "I'm appreciative of your hard work.", 'positive');
manager.addDocument('en', "You've exceeded my expectations.", 'positive');
manager.addDocument('en', "Thanks for your exceptional support.", 'positive');
manager.addDocument('en', "Your assistance has been priceless.", 'positive');
manager.addDocument('en', "I'm extremely pleased with your service.", 'positive');
manager.addDocument('en', "You're an outstanding professional.", 'positive');
manager.addDocument('en', "I value your unwavering dedication.", 'positive');
manager.addDocument('en', "You've brightened my day with your help.", 'positive');
manager.addDocument('en', "I can consistently rely on you.", 'positive');
manager.addDocument('en', "You're a star performer!", 'positive');
manager.addDocument('en', "I'm deeply thankful for your support.", 'positive');
manager.addDocument('en', "You're a true hero.", 'positive');
manager.addDocument('en', "Your help is truly priceless.", 'positive');
manager.addDocument('en', "You're an invaluable asset to the team.", 'positive');
manager.addDocument('en', "I hope you continue to thrive.", 'positive');
manager.addDocument('en', "I'm thrilled with your service.", 'positive');
manager.addDocument('en', "This has exceeded my expectations.", 'positive');
manager.addDocument('en', "I'm genuinely impressed by your team's efforts.", 'positive');
manager.addDocument('en', "You're doing an exceptional job!", 'positive');
manager.addDocument('en', "Kudos for your outstanding support.", 'positive');




manager.addDocument('en', "This is frustrating to deal with.", 'negative');
manager.addDocument('en', "I'm disappointed with the outcome.", 'negative');
manager.addDocument('en', "I'm not satisfied with this service.", 'negative');
manager.addDocument('en', "I'm annoyed by this situation.", 'negative');
manager.addDocument('en', "I'm not happy with the quality.", 'negative');
manager.addDocument('en', "I'm concerned about this issue.", 'negative');
manager.addDocument('en', "This is really bothering me.", 'negative');
manager.addDocument('en', "I'm not pleased with the response.", 'negative');
manager.addDocument('en', "I'm let down by the lack of support.", 'negative');
manager.addDocument('en', "This is not what I expected.", 'negative');
manager.addDocument('en', "I find this incredibly frustrating.", 'negative');
manager.addDocument('en', "This situation is quite disappointing.", 'negative');
manager.addDocument('en', "I'm extremely dissatisfied with the service.", 'negative');
manager.addDocument('en', "Dealing with this is really annoying.", 'negative');
manager.addDocument('en', "The quality here is far from satisfactory.", 'negative');
manager.addDocument('en', "I'm deeply concerned about this issue.", 'negative');
manager.addDocument('en', "This issue is causing me a lot of distress.", 'negative');
manager.addDocument('en', "I'm thoroughly displeased with the response.", 'negative');
manager.addDocument('en', "The lack of support is a major letdown.", 'negative');
manager.addDocument('en', "This falls far short of my expectations.", 'negative');
manager.addDocument('en', "I'm very disappointed with this outcome.", 'negative');
manager.addDocument('en', "This is frustrating and unacceptable.", 'negative');
manager.addDocument('en', "I'm upset about this situation.", 'negative');
manager.addDocument('en', "This is a major letdown.", 'negative');
manager.addDocument('en', "I'm not satisfied with the quality.", 'negative');
manager.addDocument('en', "This is a complete failure.", 'negative');
manager.addDocument('en', "I'm so frustrated right now.", 'negative');
manager.addDocument('en', "This is terrible news.", 'negative');
manager.addDocument('en', "I can't believe how disappointing this is.", 'negative');
manager.addDocument('en', "I'm very displeased with your service.", 'negative');
manager.addDocument('en', "I don't think I can do it.", 'negative');
manager.addDocument('en', "This is incredibly frustrating.", 'negative');
manager.addDocument('en', "I'm extremely disappointed with this outcome.", 'negative');
manager.addDocument('en', "I'm really dissatisfied with this service.", 'negative');
manager.addDocument('en', "I'm irritated by this situation.", 'negative');
manager.addDocument('en', "I'm not happy with the quality at all.", 'negative');
manager.addDocument('en', "I'm deeply concerned about this issue.", 'negative');
manager.addDocument('en', "This is causing me a lot of distress.", 'negative');
manager.addDocument('en', "I'm thoroughly displeased with the response.", 'negative');
manager.addDocument('en', "The lack of support is disappointing.", 'negative');
manager.addDocument('en', "This falls short of my expectations.", 'negative');
manager.addDocument('en', "I'm very frustrated right now.", 'negative');
manager.addDocument('en', "This is terrible news.", 'negative');
manager.addDocument('en', "I can't believe how disappointing this is.", 'negative');
manager.addDocument('en', "I'm very displeased with your service.", 'negative');
manager.addDocument('en', "I don't think I can continue like this.", 'negative');
manager.addDocument('en', "This is beyond frustrating.", 'negative');
manager.addDocument('en', "I'm fed up with this situation.", 'negative');
manager.addDocument('en', "I'm extremely disappointed in your support.", 'negative');
manager.addDocument('en', "This is a major letdown.", 'negative');
manager.addDocument('en', "I'm not satisfied with your performance at all.", 'negative');
manager.addDocument('en', "This is maddening to deal with.", 'negative');
manager.addDocument('en', "I'm disheartened by the outcome.", 'negative');
manager.addDocument('en', "I'm dissatisfied with this service.", 'negative');
manager.addDocument('en', "I'm irritated by this situation.", 'negative');
manager.addDocument('en', "I'm displeased with the quality.", 'negative');
manager.addDocument('en', "I'm troubled by this issue.", 'negative');
manager.addDocument('en', "This is genuinely bothering me.", 'negative');
manager.addDocument('en', "I'm let down by the response.", 'negative');
manager.addDocument('en', "I'm disappointed in the lack of support.", 'negative');
manager.addDocument('en', "This is far from what I expected.", 'negative');
manager.addDocument('en', "I'm finding this incredibly vexing.", 'negative');
manager.addDocument('en', "This situation is profoundly disheartening.", 'negative');
manager.addDocument('en', "I'm highly dissatisfied with the service.", 'negative');
manager.addDocument('en', "Dealing with this is truly exasperating.", 'negative');
manager.addDocument('en', "The quality here leaves much to be desired.", 'negative');
manager.addDocument('en', "I'm deeply troubled by this issue.", 'negative');
manager.addDocument('en', "This issue is causing me significant distress.", 'negative');
manager.addDocument('en', "I'm utterly disappointed with the response.", 'negative');
manager.addDocument('en', "The lack of support is a considerable letdown.", 'negative');
manager.addDocument('en', "This falls disappointingly short of my expectations.", 'negative');
manager.addDocument('en', "I'm thoroughly dismayed by this outcome.", 'negative');
manager.addDocument('en', "This is highly frustrating and unsatisfactory.", 'negative');
manager.addDocument('en', "I'm deeply upset about this situation.", 'negative');
manager.addDocument('en', "This is a major disappointment.", 'negative');
manager.addDocument('en', "I'm thoroughly unsatisfied with the quality.", 'negative');
manager.addDocument('en', "This is an absolute failure.", 'negative');
manager.addDocument('en', "I'm incredibly frustrated right now.", 'negative');
manager.addDocument('en', "This is awful news.", 'negative');
manager.addDocument('en', "I can't believe how disheartening this is.", 'negative');
manager.addDocument('en', "I'm profoundly dissatisfied with your service.", 'negative');
manager.addDocument('en', "I'm unsure if I can handle it.", 'negative');
manager.addDocument('en', "This is unbelievably frustrating.", 'negative');
manager.addDocument('en', "I'm extremely dismayed by this outcome.", 'negative');
manager.addDocument('en', "I'm very unsatisfied with this service.", 'negative');
manager.addDocument('en', "I'm aggravated by this situation.", 'negative');
manager.addDocument('en', "I'm not pleased with the quality at all.", 'negative');
manager.addDocument('en', "I'm deeply troubled by this issue.", 'negative');
manager.addDocument('en', "This is causing me significant anguish.", 'negative');
manager.addDocument('en', "I'm thoroughly discontented with the response.", 'negative');
manager.addDocument('en', "The lack of support is frustrating.", 'negative');
manager.addDocument('en', "This is a considerable letdown.", 'negative');
manager.addDocument('en', "I'm unsatisfied with your performance at all.", 'negative');
manager.addDocument('en', "I'm unsure if I can continue like this.", 'negative');
manager.addDocument('en', "This is beyond infuriating.", 'negative');
manager.addDocument('en', "I'm fed up with this situation.", 'negative');
manager.addDocument('en', "I'm extremely dismayed in your support.", 'negative');
manager.addDocument('en', "This is a significant disappointment.", 'negative');
manager.addDocument('en', "I'm deeply dissatisfied with your performance.", 'negative');

(async () => {
    await manager.train();
    manager.save();
})();
