const { NlpManager } = require('node-nlp');
const manager = new NlpManager({ languages: ['en', 'sp'], forceNER: true });

manager.addDocument('en', "Could you make this change?", 'request');
manager.addDocument('en', "I suggest we update this part.", 'request');
manager.addDocument('en', "It would be cool if you could add", 'request');
manager.addDocument('en', "It would be great if this could be improved:", 'request');
manager.addDocument('en', "Could you consider changing", 'request');
manager.addDocument('en', "Perhaps you could enhance", 'request');
manager.addDocument('en', "Is it possible to modify", 'request');
manager.addDocument('en', "Can you add functionality for", 'request');
manager.addDocument('en', "I'd like to request a feature:", 'request');
manager.addDocument('en', "I need this part to be updated:", 'request');
manager.addDocument('en', "Please help me with this change:", 'request');
manager.addDocument('en', "Could you assist me in implementing", 'request');
manager.addDocument('en', "I'm looking for an improvement in", 'request');
manager.addDocument('en', "Would you mind adding support for", 'request');
manager.addDocument('en', "I want you to change", 'request');
manager.addDocument('en', "You should totally", 'request');
manager.addDocument('en', "It'd be awesome if", 'request');
manager.addDocument('en', "You gotta", 'request');
manager.addDocument('en', "Can you, like, please", 'request');
manager.addDocument('en', "Maybe you could, like,", 'request');
manager.addDocument('en', "Is it like possible to", 'request');
manager.addDocument('en', "Could you hook me up with", 'request');
manager.addDocument('en', "I'd love to see some", 'request');
manager.addDocument('en', "I need this to be more", 'request');
manager.addDocument('en', "Help me out with", 'request');
manager.addDocument('en', "Could you, like, assist me in", 'request');
manager.addDocument('en', "I'm really into", 'request');
manager.addDocument('en', "Would you mind adding", 'request');
manager.addDocument('en', "I want you to make it", 'request');

manager.addDocument('en', "Can you provide more details?", 'question');
manager.addDocument('en', "Could you explain further?", 'question');
manager.addDocument('en', "I'd like more information about this.", 'question');
manager.addDocument('en', "Could you help me understand better?", 'question');
manager.addDocument('en', "Can you clarify something for me?", 'question');
manager.addDocument('en', "I need more info on this topic.", 'question');
manager.addDocument('en', "Can you explain the process?", 'question');
manager.addDocument('en', "What are the steps to do this?", 'question');
manager.addDocument('en', "I'm curious about how to", 'question');
manager.addDocument('en', "What's the procedure to", 'question');
manager.addDocument('en', "Can you provide guidance on", 'question');
manager.addDocument('en', "I'm interested in learning more about", 'question');
manager.addDocument('en', "Can you provide insights into", 'question');
manager.addDocument('en', "Could you share more details about", 'question');
manager.addDocument('en', "I'm looking for information on", 'question');
manager.addDocument('en', "Can you give me more context on", 'question');
manager.addDocument('en', "What's the recommended way to", 'question');

manager.addDocument('en', "Great job on", 'positive');
manager.addDocument('en', "I'm impressed by", 'positive');
manager.addDocument('en', "Well done with", 'positive');
manager.addDocument('en', "I love", 'positive');
manager.addDocument('en', "You're amazing at", 'positive');
manager.addDocument('en', "Kudos for", 'positive');
manager.addDocument('en', "Excellent work on", 'positive');
manager.addDocument('en', "I'm grateful for", 'positive');
manager.addDocument('en', "You've done an awesome job on", 'positive');
manager.addDocument('en', "I'm so pleased with", 'positive');
manager.addDocument('en', "Bravo for", 'positive');
manager.addDocument('en', "I appreciate your work on", 'positive');
manager.addDocument('en', "Your effort on", 'positive');
manager.addDocument('en', "You've exceeded my expectations with", 'positive');
manager.addDocument('en', "Thanks for your support.", 'positive');
manager.addDocument('en', "I appreciate your help.", 'positive');
manager.addDocument('en', "You've been so helpful.", 'positive');
manager.addDocument('en', "Great job sending the info.", 'positive');
manager.addDocument('en', "You're the best.", 'positive');
manager.addDocument('en', "I'm grateful for your assistance.", 'positive');
manager.addDocument('en', "good", 'positive');
manager.addDocument('en', "great", 'positive');
manager.addDocument('en', "Hi there! I'm feeling great today.", 'positive');
manager.addDocument('en', "Hello, I'm having an awesome day.", 'positive');
manager.addDocument('en', "Hey! It's nice to see you again.", 'positive');
manager.addDocument('en', "Good morning! I'm in a fantastic mood.", 'positive');
manager.addDocument('en', "Hi, how's it going? I'm doing wonderfully.", 'positive');
manager.addDocument('en', "Hello, I hope you're well. I'm really happy.", 'positive');
manager.addDocument('en', "Hey, it's a beautiful day! I'm feeling cheerful.", 'positive');
manager.addDocument('en', "Good afternoon! I'm having a fantastic time.", 'positive');
manager.addDocument('en', "Hi there, friend! I'm filled with joy.", 'positive');
manager.addDocument('en', "Hello, everyone! I'm thrilled to be here.", 'positive');


manager.addDocument('en', "This is frustrating to deal with.", 'negative');
manager.addDocument('en', "I'm disappointed with the outcome.", 'negative');
manager.addDocument('en', "I'm not satisfied with this service.", 'negative');
manager.addDocument('en', "I'm annoyed by this situation.", 'negative');
manager.addDocument('en', "I'm not happy with the quality.", 'negative');
manager.addDocument('en', "I'm concerned about this issue.", 'negative');
manager.addDocument('en', "This is really bothering me.", 'negative');
manager.addDocument('en', "I'm not pleased with the response.", 'negative');
manager.addDocument('en', "I'm let down by the lack of support.", 'negative');
manager.addDocument('en', "This is not what I expected.", 'negative');
manager.addDocument('en', "I find this incredibly frustrating.", 'negative');
manager.addDocument('en', "This situation is quite disappointing.", 'negative');
manager.addDocument('en', "I'm extremely dissatisfied with the service.", 'negative');
manager.addDocument('en', "Dealing with this is really annoying.", 'negative');
manager.addDocument('en', "The quality here is far from satisfactory.", 'negative');
manager.addDocument('en', "I'm deeply concerned about this issue.", 'negative');
manager.addDocument('en', "This issue is causing me a lot of distress.", 'negative');
manager.addDocument('en', "I'm thoroughly displeased with the response.", 'negative');
manager.addDocument('en', "The lack of support is a major letdown.", 'negative');
manager.addDocument('en', "This falls far short of my expectations.", 'negative');



(async () => {
    await manager.train();
    manager.save();
})();
